# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gradual' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gradual
  pod 'lottie-ios'
  pod 'Stripe'
  pod 'Alamofire', '~> 5.1'
  pod 'AlamofireImage', '~> 4.1'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SVProgressHUD'

  target 'gradualTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'gradualUITests' do
    # Pods for testing
  end

end
